import mongoose from "mongoose";

const LensSaleSchema = new mongoose.Schema(
  {
    billData: {
      billSeries: { type: String, default: "" },
      billNo: { type: String, default: "" },
      date: { type: Date, default: Date.now },
      billType: { type: String, default: "" },
      bankAccount: { type: String, default: "" },
      godown: { type: String, default: "" },
      bookedBy: { type: String, default: "" },
    },
    partyData: {
      partyAccount: { type: String, default: "" },
      address: { type: String, default: "" },
      contactNumber: { type: String, default: "" },
      stateCode: { type: String, default: "" },
      creditLimit: { type: Number, default: 0 },
      CurrentBalance: {
        amount: { type: Number, default: 0 },
        type: { type: String, enum: ["Dr", "Cr"], default: "Dr" },
      },
    },
    items: [
      {
        barcode: { type: String, default: "" },
        itemName: { type: String, default: "" },
        billItemName: { type: String, default: "" },
        vendorItemName: { type: String, default: "" },
        unit: { type: String, default: "" },
        dia: { type: String, default: "" },
        eye: { type: String, default: "" },
        sph: { type: Number, default: 0 },
        cyl: { type: Number, default: 0 },
        axis: { type: Number, default: 0 },
        add: { type: Number, default: 0 },
        qty: { type: Number, default: 0 },
        salePrice: { type: Number, default: 0 },
        discount: { type: Number, default: 0 },
        totalAmount: { type: Number, default: 0 },
        sellPrice: { type: Number, default: 0 },
        purchasePrice: { type: Number, default: 0 },
        combinationId: { type: String, default: "" },
        orderNo: { type: String, default: "" },
        remark: { type: String, default: "" },
        // Item-level status tracking
        itemStatus: {
          type: String,
          enum: ["Pending", "In Progress", "Done", "Cancelled"],
          default: "Pending"
        },
      },
    ],
    taxes: [
      {
        taxName: { type: String, default: "" },
        type: { type: String, default: "Additive" },
        percentage: { type: Number, default: 0 },
        amount: { type: Number, default: 0 },
        meta: { type: mongoose.Schema.Types.Mixed, default: {} },
      },
    ],
    grossAmount: { type: Number, default: 0 }, // sum of (qty * purchasePrice) - (discount amounts) OR as you define
    subtotal: { type: Number, default: 0 }, // sum of item.totalAmount (before taxes)
    taxesAmount: { type: Number, default: 0 }, // sum of taxes.amount
    netAmount: { type: Number, default: 0 }, // subtotal + taxesAmount
    paidAmount: { type: Number, default: 0 }, // amount paid now (if none then 0)
    dueAmount: { type: Number, default: 0 }, // netAmount - paidAmount
    deliveryDate: { type: Date, default: Date.now() },
    summary: {
      totalQty: { type: Number, default: 0 },
      totalAmount: { type: Number, default: 0 },
    },
    time: {
      type: String,
      default: () => new Date().toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata" }),
    },
    remark: { type: String, default: "" },
    // Parent-level status derived from item statuses
    parentStatus: {
      type: String,
      enum: ["Pending", "In Progress", "Done", "Cancelled"],
      default: "Pending"
    },
    // Legacy status field - kept for backward compatibility
    status: {
      type: String,
      default: "Pending",
      enum: ["Pending", "In Progress", "Done", "Cancelled"],
    },
    // Delivery tracking fields
    outForDeliveryTime: { type: Date, default: null },
    arrivedTime: { type: Date, default: null },
    deliveredTime: { type: Date, default: null },
    dispatchTime: { type: Date, default: null },
    deliveryCompletionTime: { type: Date, default: null },
    deliveryOtp: { type: String, default: null },
    otpExpiresAt: { type: Date, default: null },
    deliveryStatus: {
      type: String,
      enum: ["Pending", "Out for Delivery", "Arrived", "Delivered"],
      default: "Pending"
    },
    arrivalTime: { type: Date, default: null },
    travelDuration: { type: Number, default: 0 }, // Duration in minutes from arrival to completion
    sourceChallanId: { type: mongoose.Schema.Types.ObjectId, ref: "SaleChallan", default: null }, // Reference to source challan if created from challan
    sourceSaleId: { type: String, default: null }, // Reference to source sale order
    autoGenerated: { type: Boolean, default: false },
    deliveryPerson: { type: String, default: "" },
    createdBy: { type: String, default: "USER" },
    settlementDate: { type: Date, default: null }, // Date when this transaction was settled/reconciled
    companyId: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', default: null },
  },
  { timestamps: true }
);

const LensSale = mongoose.model("LensSale", LensSaleSchema);
export default LensSale;
